### ISSUE TITLE
能否下载下来直接使用呢?

### ISSUE THREAD

**Issue by airenqingqing** [OracleChain/EOSDevHelper#1]

**Comment by spartucus** [comment]
马上会有Windows 的release版本。

**Comment by spartucus** [comment]
@airenqingqing 
[download](https://github.com/OracleChain/EOSDevHelper/releases)

**Comment by TeddyTsui** [comment]
漏了打包plugin？运行提示找不到 Qt platform plugin “window”

**Comment by spartucus** [comment]
@TeddyTsui 多谢，已修复。
