### ISSUE TITLE
交易数据序列化的问题

### ISSUE THREAD

**Issue by lucas556** [OracleChain/EOSDevHelper#2]
你好,感谢oraclechain提供这么好的工具给大家用,在使用中,或者说我对eos的不了解吧,走了不少弯路,有了eosdevhelper后能直观的对比数据和结果.

```
{
"compression": "none",
"packed_context_free_data": "00",
"packed_trx": "779ee15a00006b7d7d3b39c000000000010000000000ea305500409e9a2264b89a01000000005c955cc500000000a8ed32327c000000005c955cc5000000000037067501000000010002c6bd40b5e5a344fcd7e8ff782e782dc84d987b19304006f8d9b656531248c9670100000100000001000300e43ac18a3c3cee0aacf83fc42267062c5bf1dc8ba35792589dd01671bcd079010000010000000001000000005c955cc500000000a8ed32320100",
"signatures": [
"EOSKh6eQHoiza8y1bT1XFFFpZCvBRsc9Hbc8Zb7yjwVHuGXJ3PqHUiLqmzjEeZUc9RmrQism8EaVijL5sXaMkTKj4DZvPeCfG"
]
}
```

基于上面的json,我的问题是:
这里的packed_trx是如何得到的,我看了下,它是使用zlib压缩的,但是又和get required key里的data有关系?

**Comment by spartucus** [comment]
目前packed_trx不是zlib压缩的，它就是普通序列化的结果。get_required_keys请求里的data，其实是abi_json_to_bin返回的响应的结果。abi_json_to_bin是利用nodeos来进行序列化。

**Comment by lucas556** [comment]
@spartucus 谢谢,请问eos里对交易数据进行签名后都进行了那些处理呢?或者说,使用ecdsa secp256k1标准签名还要进行处理吗

**Comment by spartucus** [comment]
[packPushTransactionParam()](https://github.com/OracleChain/EOSDevHelper/blob/master/src/push/pushframe.cpp#L90)是准备push_transaction的请求参数。你问的这些，可以从这儿开始看。
