### ISSUE TITLE
Can not create a new account

### ISSUE THREAD

**Issue by cirthdev** [OracleChain/EOSDevHelper#3]
While I trying to create a new account, got the error message:
```
{

"code": 401,

"error": {

"code": 3030002,

"details": [

{

"file": "chain_controller.cpp",

"line_number": 985,

"message": "transaction declares authority '{\"actor\":\"eosio\",\"permission\":\"active\"}', but does not have signatures for it.",

"method": "get_required_keys"

}

],

"name": "tx_missing_sigs",

"what": "signatures do not satisfy declared authorizations"

},

"message": "UnAuthorized"

}
```
But it's ok while I create account by curl: 
curl http://localhost:8888 create account eosio myaccount01 ${public_key_1} ${public_key_2} eosio

**Comment by spartucus** [comment]
Did you unlock the wallet that imported eosio's private key?

**Comment by shishi614** [comment]
i  unlock the wallet  ,the same problem

**Comment by spartucus** [comment]
Could you post the `get_required_keys` request here?

**Comment by spartucus** [comment]
Looks like that EOS's signature has changed during last few days. I will work on this.

**Comment by issaxyz** [comment]
Supposing you are using the master branch, which may involves some changes we didn't adapt to. Thus we recommend you using tag DAWN-2018-04-27-ALPHA.

We would release with our tags according/adapt to the official tags now. @spartucus
