### ISSUE TITLE
More detailed instructions on how to compile on OSX

### ISSUE THREAD

**Issue by Soleone** [OracleChain/EOSDevHelper#5]
I'm used to build scripts one could call in a single command to build an executable, but not sure how QT does it.

Maybe just a few sentences in the compile section would help clarify how exactly it works to get it compiled. Bonus points for offering a precompiled `.dmg` or `.zip` file in the Releases section ;)

Might help get more people trying and using the tool, I was close to just silently giving up.

**Comment by issaxyz** [comment]
yeah, we need to add our OSX release  file in **.zip** now, appreciate your suggestion,and the compile instruction would be carried out in the next week or so.

**Comment by issaxyz** [comment]
@Soleone hey Sole~glad to inform you our Mac version is avaliable now:https://github.com/OracleChain/EOSDevHelper/releases/download/1.0/EOSDevHelper_OSX_Release.zip
