### ISSUE TITLE
下载的EOSDevHelper_Windows_Release_Dawn4.zip版本无法使用

### ISSUE THREAD

**Issue by wangyilin1987** [OracleChain/EOSDevHelper#7]
Settings 连接节点没有任何反应

**Comment by spartucus** [comment]
我在本地测试了一下，可以连接。
可以排查以下几个方面的问题：
1. 单纯的ping节点ip，能通吗？
2. 节点是否启动，是什么版本。这个Release包支持4.0及以上eos版本。

如果安装了Qt，最好是用最新的代码，自己编译程序，使用生成的程序。

此问题未复现，暂时关闭，如果上述方法没有解决你的问题，请再打开。
