### ISSUE TITLE
Ubuntu - Invalid use of incomplete type 'class QTabBar'

### ISSUE THREAD

**Issue by mgravitt** [OracleChain/EOSDevHelper#8]
Hi - I am attempting to run on Ubuntu (kubuntu). When I attempt to build in Qt, I get an error of invalid use of incomplete type 'class QTabBar'  for this line:

`ui->tabWidget->tabBar()->setStyle(std::move(new CustomTabStyle));`

mainwindow.cpp, line 23

I am running Qt5.10.1 from June 5 2018.

Any ideas?

thanks

**Comment by mgravitt** [comment]
I tried commenting out that line as well as two other lines causing an issue wtih QRegExpValidator. I believe that it was able to build but I get the attached errors. I must be running something incompatible.

![image](https://user-images.githubusercontent.com/32852271/42596688-8b8d5ff8-8524-11e8-8cc1-f8085971c669.png)

**Comment by spartucus** [comment]
`cannot find -lGL` means lacks of OpenGL libraries, please see [wiki](https://github.com/OracleChain/EOSDevHelper/wiki#ubuntu-1604).

I should add this to readme instead of wiki. Thanks for reporting.
